"""Proposal: the five 'pending' queue rows from the 17 Sep 2026 framework-currency check (handover Open work 4).
_src/_conf are verification metadata, not written."""
D="October 2026"
POL=[
dict(Record_ID="POL-112", Name="Carbon Budget and Growth Delivery Plan (CBGDP)", Acronym="CBGDP", Record_Type="Policy_Activity",
 General_Type="Plan", Policy_Sector="Climate | Energy | Transport | Urban & Buildings | Land Use & Agriculture", Year_Status="2025 (published 29 Oct 2025, HC 1366; factsheets added Jun 2026)",
 Statutory_Status="Statutory", Enabling_Legislation="[LEG-001]; [LEG-003]", Related_Policy_Links="[POL-004] Carbon Budget Delivery Plan 2023 (superseded); [POL-018] Seventh Carbon Budget; [POL-114] CCC progress reports",
 Lead_Organisation="[ORG-002] DESNZ",
 Scope_And_Commitments="The government's report under section 14 of the Climate Change Act 2008 setting out how it will meet its statutory carbon budgets and secure the economic benefits of the transition; replaces the Carbon Budget Delivery Plan 2023 [POL-004] as the plan against which the CCC assesses progress. Main report with a technical annex and sector investor factsheets. The CCC indicator benchmarks in [IFW-02] were re-derived against it (indicators v18–v20).",
 Extent="UK", Date_Last_Updated=D, Link="https://www.gov.uk/government/publications/carbon-budget-and-growth-delivery-plan-2025", Indicator_Frameworks="[IFW-02]",
 _src="gov.uk publication page", _conf="High. Supersession of CBDP 2023 is the CCC's and the workbook's existing reading; the gov.uk page does not state it"),
dict(Record_ID="POL-113", Name="A Well-Adapted UK — Fourth Independent Assessment of UK Climate Risk (CCRA4-IA)", Acronym="CCRA4-IA", Record_Type="Policy_Activity",
 General_Type="Assessment / Evidence", Policy_Sector="Climate | Health | Nature & Biodiversity | Water | Governance, Society & Data", Year_Status="2026 (published 20 May 2026)",
 Statutory_Status="Statutory", Enabling_Legislation="[LEG-001]", Related_Policy_Links="[POL-017] CCRA3 2022; [POL-002] NAP3",
 Lead_Organisation="[ORG-003] CCC",
 Scope_And_Commitments="The CCC's statutory independent assessment of UK climate risk under section 57 of the Climate Change Act 2008, covering all four nations across 14 systems, assessed for 2°C of global warming by 2050 with 4°C by 2100 considered; prioritises eight highest-risk areas and, for the first time, proposes adaptation solutions. The Technical Report was led by the Met Office [ORG-017] (Prof Jason Lowe, Dr Mark Harrison, Rachel Perks) — a direct Met Office → policy channel. The UK Government must lay CCRA4 before Parliament by January 2027, followed by national adaptation programmes around 2028.",
 Extent="UK", Date_Last_Updated=D, Link="https://www.theccc.org.uk/publication/a-well-adapted-uk/", Indicator_Frameworks="[IFW-10]",
 _src="theccc.org.uk publication page", _conf="High"),
dict(Record_ID="POL-114", Name="CCC progress reports to Parliament (annual emissions progress reports)", Acronym="CCC Progress Reports", Record_Type="Policy_Activity",
 General_Type="Assessment / Evidence", Policy_Sector="Climate | Energy | Transport | Land Use & Agriculture | Governance, Society & Data", Year_Status="Annual (latest: Progress in reducing emissions 2026, 24 Jun 2026)",
 Statutory_Status="Statutory", Enabling_Legislation="[LEG-001]", Related_Policy_Links="[POL-112] CBGDP; [POL-018] Seventh Carbon Budget",
 Lead_Organisation="[ORG-003] CCC",
 Scope_And_Commitments="The CCC's annual statutory report to Parliament on progress towards the carbon budgets and net zero, laid under section 36(1) of the Climate Change Act 2008: emissions trends, sectoral performance, and the credibility of government policy — the 2026 report assesses the CBGDP [POL-112]. Held as one record for the series, not one per year. The CCC's separate adaptation progress reporting is not covered here.",
 Extent="UK", Date_Last_Updated=D, Link="https://www.theccc.org.uk/publication/progress-in-reducing-emissions-2026-report-to-parliament/", Indicator_Frameworks="[IFW-02]",
 _src="theccc.org.uk 2026 report page", _conf="High. DECISION: one series record rather than the 2026 report alone (level-of-generality rule); the Link is the latest report"),
dict(Record_ID="POL-115", Name="Third Northern Ireland Climate Change Adaptation Programme (NICCAP3)", Acronym="NICCAP3", Record_Type="Policy_Activity",
 General_Type="Plan", Policy_Sector="Climate | Water | Health | Nature & Biodiversity | Governance, Society & Data", Year_Status="2026 (published 19 Mar 2026; runs to 2029)",
 Statutory_Status="Statutory", Enabling_Legislation="[LEG-001]", Related_Policy_Links="[POL-002] NAP3 (England); [POL-017] CCRA3 2022",
 Lead_Organisation="[ORG-036] Northern Ireland Executive (DAERA)",
 Scope_And_Commitments="Northern Ireland's statutory adaptation programme under section 60 of the Climate Change Act 2008, responding to the risks identified in CCRA3: over 280 actions from across NI Executive departments and wider stakeholders, covering flooding, heatwaves, severe storms and other climate impacts. Northern Ireland counterpart of NAP3 [POL-002].",
 Extent="Northern Ireland", Date_Last_Updated=D, Link="https://www.daera-ni.gov.uk/publications/third-northern-ireland-climate-change-adaptation-programme",
 _src="DAERA publication page", _conf="High"),
dict(Record_ID="POL-116", Name="Scotland's Climate Change Plan 2026–2040", Acronym="CCP 2026–40", Record_Type="Policy_Activity",
 General_Type="Plan", Policy_Sector="Climate | Energy | Transport | Land Use & Agriculture | Urban & Buildings", Year_Status="2026 (final plan published 24 Mar 2026; draft 6 Nov 2025)",
 Statutory_Status="Statutory", Enabling_Legislation="[LEG-058]", Related_Policy_Links="[POL-112] CBGDP (UK)",
 Lead_Organisation="[ORG-034] Scottish Government",
 Scope_And_Commitments="Scotland's statutory plan setting out policies and proposals to meet its first three carbon budgets (2026–2030, 2031–2035, 2036–2040) on the path to net zero by 2045, with sectoral contributions, costs and benefits, and just-transition measures. The CCC assessed the draft (Feb 2026) as credible or low-risk for 91% of the reductions needed in the first budget, with significant risks for later budgets. Scottish counterpart of the UK CBGDP [POL-112].",
 Extent="Scotland", Date_Last_Updated=D, Link="https://www.gov.scot/publications/scotlands-climate-change-plan-2026-2040-annexes/",
 _src="gov.scot climate change 'latest' page (dates); gov.scot plan pages; CCC news 25 Feb 2026", _conf="High on dates and budgets. Statutory basis (Climate Change (Scotland) Act 2009 s.35, [LEG-058]) inherited, not re-read"),
]
EDITS=[
("Policies & Activities","POL-004","Scope_And_Commitments","A separate record for the CBGDP is queued.","The CBGDP is held as [POL-112]."),
("Policies & Activities","POL-004","Related_Policy_Links",None,"[POL-112] Carbon Budget and Growth Delivery Plan (CBGDP)"),
("Policies & Activities","POL-017","Scope_And_Commitments","A separate record for CCRA4-IA is queued.","CCRA4-IA is held as [POL-113]; the government must lay CCRA4 before Parliament by January 2027."),
("Policies & Activities","POL-017","Related_Policy_Links",None,"[POL-113] CCRA4-IA (May 2026)"),
]
