"""Proposed records for UK governance v27 (and international v17) — Open work item 1, 6 October 2026.
Data only. `_src`, `_conf` and `_note` keys are proposal metadata and are NOT written to the workbook.
"""
D = "October 2026"

LEG = [
dict(Record_ID="LEG-068", Name="Natural Environment (Scotland) Act 2026", Record_Type="Legislation",
 General_Type="Primary Legislation", Policy_Sector="Nature & Biodiversity | Land Use & Agriculture | Marine & Fisheries",
 Statutory_Enabling_Basis="Primary Act of the Scottish Parliament (2026 asp 6) — self-authorising.",
 Enabling_Legislation="[LEG-068]", Year="2026", Extent="Scotland",
 Key_Provisions="Part 1 requires Scottish Ministers to set statutory targets for improving biodiversity (habitat condition, species status and environmental conditions) with accompanying monitoring and compliance reporting; Environmental Standards Scotland [ORG-045] has an independent assurance role. Part 2 amends National Park aims, adds national park policy statements, a duty on public bodies to facilitate implementation of park plans, and fixed-penalty byelaw enforcement. Part 3 reforms deer management (revised aims, code of practice, management plans and control schemes, NatureScot investigatory powers). Part 4 covers swift nest boxes in new buildings, climate adaptation for marine protected areas, salmon and freshwater fishing offences, gull reporting, wildlife licensing, wildfire, forestry and muirburn licensing. The biodiversity targets and their indicators are not yet set; when published they are IFW and IND candidates.",
 Lead_Department="[ORG-034] Scottish Government (NatureScot)", Status="Royal Assent 12 Mar 2026 (commencement phased, incl. SSI 2026/275)",
 Date_Last_Updated=D, Link="https://www.legislation.gov.uk/asp/2026/6/contents",
 _src="legislation.gov.uk contents page (fetched 6 Oct); Royal Assent date from the 2 Sep scan (primary)", _conf="High on structure and provisions; medium on commencement detail"),
dict(Record_ID="LEG-069", Name="Environment (Principles, Governance and Biodiversity Targets) (Wales) Act 2026", Record_Type="Legislation",
 General_Type="Primary Legislation", Policy_Sector="Nature & Biodiversity | Governance, Society & Data",
 Statutory_Enabling_Basis="Act of Senedd Cymru (2026 asc 4) — self-authorising.",
 Enabling_Legislation="[LEG-069]", Year="2026", Extent="Wales",
 Key_Provisions="Part 1 sets an environmental objective and environmental principles that Welsh Ministers, Natural Resources Wales [ORG-015] and other public authorities must apply, with integration statements. Part 2 establishes the Office of Environmental Governance Wales [ORG-046] (strategy, monitoring of environmental law, advice, information notices, investigations, compliance notices, improvement reports). Part 3 amends the Environment (Wales) Act 2016 [LEG-035] to create a framework of statutory biodiversity targets aimed at halting and reversing biodiversity decline, with progress reporting. Targets not yet set.",
 Lead_Department="[ORG-035] Welsh Government", Status="In force (phased commencement: most of Parts 1–3 from 27 Jun 2026; ss.3–5 from 31 Mar 2027; remainder by order)",
 Date_Last_Updated=D, Link="https://www.legislation.gov.uk/asc/2026/4/contents", Related_Legislation="[LEG-035]",
 _src="legislation.gov.uk contents; gov.wales Act page (Royal Assent 27 Apr 2026, commencement dates)", _conf="High"),
dict(Record_ID="LEG-070", Name="Building Act 1984", Record_Type="Legislation",
 General_Type="Primary Legislation", Policy_Sector="Urban & Buildings",
 Statutory_Enabling_Basis="Primary Act of Parliament (1984 c. 55) — self-authorising.",
 Enabling_Legislation="[LEG-070]", Year="1984", Extent="England | Wales",
 Key_Provisions="Section 1 and Schedule 1 empower the making of building regulations (the Building Regulations 2010 and their Parts, including Part O overheating [POL-074] and Part L energy efficiency). Extensively amended, including by the Building Safety Act 2022 (higher-risk buildings, Building Safety Regulator). Held as the enabling legislation for building-standard policy records.",
 Lead_Department="[ORG-021] MHCLG", Status="In force (as amended)",
 Date_Last_Updated=D, Link="https://www.legislation.gov.uk/ukpga/1984/55/contents",
 _src="legislation.gov.uk contents", _conf="High"),
dict(Record_ID="LEG-071", Name="The Northern Ireland Climate Commissioner Regulations (Northern Ireland) 2025 (SR 2025 No. 78)", Record_Type="Legislation",
 General_Type="Secondary Legislation", Policy_Sector="Climate | Governance, Society & Data",
 Statutory_Enabling_Basis="Made under section 50 of the Climate Change Act (Northern Ireland) 2022 [LEG-059].",
 Enabling_Legislation="[LEG-059]", Year="2025", Extent="Northern Ireland",
 Key_Provisions="Establishes the office of the Northern Ireland Climate Commissioner [ORG-031] and sets its functions and general powers, appointment and tenure, staffing, finance, accounts and annual reporting.",
 Lead_Department="[ORG-036] Northern Ireland Executive (The Executive Office)", Status="In force (made 8 Apr 2025; in operation 9 Apr 2025)",
 Date_Last_Updated=D, Link="https://www.legislation.gov.uk/nisr/2025/78/contents/made", Related_Legislation="[LEG-059]",
 _src="legislation.gov.uk contents (enabling power s.50); made/operation dates from the 17 Sep queue check", _conf="High"),
]

ORG = [
dict(Record_ID="ORG-045", Name="Environmental Standards Scotland", Acronym="ESS", Record_Type="Organisation",
 General_Type="Devolved Public Body", Policy_Sector="Nature & Biodiversity | Climate | Governance, Society & Data",
 Statutory_Duties="Non-ministerial office established under the UK Withdrawal from the European Union (Continuity) (Scotland) Act 2021, Part 2, Chapter 2 (s.19); independent of the Scottish Government and accountable to the Scottish Parliament. Operating since 2021.",
 Statutory_Role="[LEG-034]",
 Remit_And_Powers="Scrutinises and investigates public authorities' compliance with environmental law and the effectiveness of that law in Scotland, filling the post-EU-exit enforcement gap. Covers all public authorities, including the Scottish Government and its agencies, local authorities and bodies with public functions. Assures Scotland's statutory biodiversity targets under the Natural Environment (Scotland) Act 2026 [LEG-068]. Signed a memorandum of understanding with the Climate Change Committee [ORG-003] on joint working (23 Jul 2026). Scottish counterpart of [ORG-007] OEP and [ORG-046] OEGW.",
 Regulatory_Powers_Keywords="Watchdog · Investigator · Information notice issuer · Compliance notice issuer · Improvement reports · Litigant (judicial review) · Independent of government",
 Extent="Scotland", Lead_Department="[ORG-034] Scottish Govt", Date_Last_Updated=D,
 Link="https://www.environmentalstandards.scot/", Related_Bodies="[ORG-007]",
 _src="environmentalstandards.scot 'What we do'; legislation.gov.uk 2021 asp 4 contents; theccc.org.uk MoU page", _conf="High. Lead_Department records the Scottish administration for diagram placement; ESS is accountable to Parliament, which the prose states"),
dict(Record_ID="ORG-046", Name="Office of Environmental Governance Wales", Acronym="OEGW", Record_Type="Organisation",
 General_Type="Devolved Public Body", Policy_Sector="Nature & Biodiversity | Governance, Society & Data",
 Statutory_Duties="Established by Part 2 of the Environment (Principles, Governance and Biodiversity Targets) (Wales) Act 2026 [LEG-069] (Royal Assent 27 Apr 2026; Part 2 largely commenced 27 Jun 2026).",
 Statutory_Role="[LEG-069]",
 Remit_And_Powers="Independent statutory body overseeing public authorities' compliance with environmental law in Wales: publishes a strategy, monitors and reports on the implementation of environmental law, advises Welsh Ministers, receives representations, issues information notices, conducts investigations, issues compliance notices and improvement reports, and can require improvement plans. Welsh counterpart of [ORG-007] OEP and [ORG-045] ESS. Operational status (board, chief executive) not confirmed at source as of October 2026.",
 Regulatory_Powers_Keywords="Watchdog · Investigator · Information notice issuer · Compliance notice issuer · Improvement reports · Independent of government",
 Extent="Wales", Lead_Department="[ORG-035] Welsh Govt", Date_Last_Updated=D,
 Link="https://www.gov.wales/environment-principles-governance-and-biodiversity-targets-wales-act-2026", Related_Bodies="[ORG-007]; [ORG-045]",
 _src="legislation.gov.uk 2026 asc 4 contents; gov.wales Act page", _conf="High on functions; operational status unverified (stated in prose)"),
dict(Record_ID="ORG-047", Name="UK Health Security Agency", Acronym="UKHSA", Record_Type="Organisation",
 General_Type="Executive Agency", Policy_Sector="Health | Climate | Pollution & Waste",
 Statutory_Duties="Executive agency of the Department of Health and Social Care; operational from 1 October 2021 (succeeding Public Health England's health-protection functions).",
 Remit_And_Powers="Protects people from health threats: infectious disease, chemicals, radiation, the health effects of climate change and environmental hazards including air quality. Runs the Weather-Health Alerting system with the Met Office [POL-072] and publishes the Adverse Weather and Health Plan [POL-073]; hosts the Centre for Climate and Health Security. Owner of heat-mortality statistics underlying [IND-C-130].",
 Regulatory_Powers_Keywords="Science provider · Data authority · Statutory adviser",
 Extent="UK | England", Lead_Department="[ORG-049] DHSC", Date_Last_Updated=D,
 Link="https://www.gov.uk/government/organisations/uk-health-security-agency",
 _src="gov.uk organisation page", _conf="High; 1 Oct 2021 operational date inherited, not re-read. Sponsor DHSC added as ORG-049 (Jonathan, 6 Oct 2026)"),
dict(Record_ID="ORG-048", Name="Local Nature Partnerships (collective)", Acronym="LNPs", Record_Type="Organisation",
 General_Type="Non-governmental body / Partnership", Policy_Sector="Nature & Biodiversity | Governance, Society & Data",
 Remit_And_Powers="Locally led, government-recognised partnerships of local organisations, businesses and people working to improve the local natural environment across England. Introduced by the 2011 Natural Environment White Paper. Advise local decision-makers and support Local Nature Recovery Strategies [POL-014]. No statutory powers. Held as a collective record, as for [ORG-037] Local Authorities.",
 Regulatory_Powers_Keywords="Advisory only · No statutory or regulatory powers",
 Extent="England", Lead_Department="[ORG-001] Defra", Date_Last_Updated=D,
 Link="https://www.gov.uk/government/publications/map-of-local-nature-partnerships", Affecting_Policies="[POL-014]",
 _src="gov.uk map of LNPs (Defra / Natural England, updated 17 Jul 2026)", _conf="High on existence and role; 2011 White Paper origin inherited"),
dict(Record_ID="ORG-049", Name="Department of Health and Social Care", Acronym="DHSC", Record_Type="Organisation",
 General_Type="Ministerial Department", Policy_Sector="Health | Climate",
 Statutory_Duties="Ministerial department supporting the Secretary of State for Health and Social Care; health is largely devolved, so its health-service remit is England with some UK-wide functions.",
 Remit_And_Powers="Leads health and social care policy. Sponsors 23 agencies and public bodies, including the UK Health Security Agency [ORG-047], which carries the climate-and-health, adverse-weather and air-quality functions held in this workbook. Added as UKHSA's sponsoring department.",
 Regulatory_Powers_Keywords="Policy-maker · Ministerial discretion · Funder · Sponsor of agencies and NDPBs",
 Extent="UK | England", Lead_Department="[ORG-049] DHSC", Date_Last_Updated=D,
 Link="https://www.gov.uk/government/organisations/department-of-health-and-social-care",
 _src="gov.uk organisation page", _conf="High"),
]

def P(**k): return k
POL = [
P(Record_ID="POL-072", Name="Heat-Health Alerting / Weather-Health Alerts (UKHSA and Met Office)", Acronym="WHA", Record_Type="Policy_Activity",
 General_Type="Operational service / System", Policy_Sector="Health | Climate", Year_Status="Impact-based since 2023 (core season 1 Jun–30 Sep; guidance updated 6 Aug 2026)",
 Statutory_Status="Non-statutory", Related_Policy_Links="[POL-073] Adverse Weather and Health Plan; [POL-075] NSWWS",
 Lead_Organisation="[ORG-047] UKHSA & [ORG-017] Met Office",
 Scope_And_Commitments="Impact-based heat-health alerts (green/yellow/amber/red) issued by UKHSA with the Met Office when forecasts identify hot-weather episodes, following a joint dynamic risk assessment; extraordinary alerts outside the core season. Cold-health alerts run in winter under the same system. Directly runs on Met Office temperature forecasts — a Met Office → policy channel.",
 Extent="England", Date_Last_Updated=D, Link="https://www.gov.uk/guidance/heat-health-alerting-system", Indicator_Frameworks="[IFW-10]",
 _src="gov.uk guidance page", _conf="High. Needs the new General_Type term"),
P(Record_ID="POL-073", Name="Adverse Weather and Health Plan", Acronym="AWHP", Record_Type="Policy_Activity",
 General_Type="Plan", Policy_Sector="Health | Climate", Year_Status="2023 (first published 27 Apr 2023; 2026–27 edition added 25 Mar 2026)",
 Statutory_Status="Non-statutory", Related_Policy_Links="[POL-002] National Adaptation Programme (NAP3); [POL-072] Weather-Health Alerts",
 Lead_Organisation="[ORG-047] UKHSA",
 Scope_And_Commitments="Plan to protect individuals and communities from the health effects of adverse weather and build resilience, replacing the Heatwave Plan and Cold Weather Plan for England; covers heat and cold with related guidance on flooding and drought. Underpinned by the Weather-Health Alerts developed with the Met Office [POL-072].",
 Extent="England", Date_Last_Updated=D, Link="https://www.gov.uk/government/publications/adverse-weather-and-health-plan", Indicator_Frameworks="[IFW-10]",
 _src="gov.uk publication page", _conf="High. The NAP3 link is a soft relation (NAP3 carries the heat-health actions); the page itself does not cite NAP3"),
P(Record_ID="POL-074", Name="Building Regulations Part O — overheating in new residential buildings (Approved Document O)", Acronym="Part O", Record_Type="Policy_Activity",
 General_Type="Standard / Code", Policy_Sector="Urban & Buildings | Health | Climate", Year_Status="2021 (published 15 Dec 2021; in force 15 Jun 2022)",
 Statutory_Status="Statutory", Enabling_Legislation="[LEG-070]", Lead_Organisation="[ORG-021] MHCLG",
 Scope_And_Commitments="Requirement in Schedule 1 to the Building Regulations 2010 that new residential buildings limit unwanted solar gains and provide means of removing excess heat. Compliance by a simplified method or by dynamic thermal modelling to CIBSE TM59 with appropriate weather files — the climate-data input. Approved Document O is the statutory guidance. Kept high-level by decision: detailed building-standard actions are out of scope.",
 Extent="England", Date_Last_Updated=D, Link="https://www.gov.uk/government/publications/overheating-approved-document-o",
 _src="gov.uk publication page", _conf="High"),
P(Record_ID="POL-075", Name="National Severe Weather Warning Service (NSWWS), including Extreme Heat warnings", Acronym="NSWWS", Record_Type="Policy_Activity",
 General_Type="Operational service / System", Policy_Sector="Climate | Health | Governance, Society & Data", Year_Status="Ongoing (impact-based matrix; Extreme Heat warning added Jun 2021)",
 Statutory_Status="Non-statutory", Related_Policy_Links="[POL-072] Weather-Health Alerts", Lead_Organisation="[ORG-017] Met Office",
 Scope_And_Commitments="The Met Office's 24/7 UK severe-weather warning service, up to seven days ahead, for rain, thunderstorms, wind, snow, lightning, ice, extreme heat and fog. Yellow/amber/red warnings from an impact × likelihood matrix. The Extreme Heat warning (introduced June 2021, developed with Public Health England) is impact-based, not a fixed temperature threshold, and is distinct from the UKHSA heat-health alerts.",
 Extent="UK", Date_Last_Updated=D, Link="https://weather.metoffice.gov.uk/guides/warnings",
 _src="Met Office warnings guide; Met Office blog 2021 (Extreme Heat introduction)", _conf="High. Record held at service level (level-of-generality rule) rather than one warning type"),
P(Record_ID="POL-076", Name="UK Plant Health Risk Register", Acronym="UK PHRR", Record_Type="Policy_Activity",
 General_Type="Operational service / System", Policy_Sector="Biosecurity | Nature & Biodiversity | Land Use & Agriculture", Year_Status="Ongoing (updated monthly; 1,443 pests at Oct 2026)",
 Statutory_Status="Non-statutory", Related_Policy_Links="[POL-034] Plant Biosecurity Strategy for GB; [POL-077] plant health contingency plans",
 Lead_Organisation="[ORG-001] Defra & devolved administrations",
 Scope_And_Commitments="Public register used by government and industry to prioritise action on plant pests and diseases. Each pest scored for likelihood of establishment and impact, with climate suitability for UK conditions an explicit component, and a mitigated risk score. Implements a recommendation of the Tree Health and Plant Biosecurity Expert Taskforce. Not a comprehensive list of regulated pests.",
 Extent="UK", Date_Last_Updated=D, Link="https://planthealthportal.defra.gov.uk/pests-and-diseases/uk-plant-health-risk-register/",
 _src="Defra plant health portal", _conf="High"),
P(Record_ID="POL-077", Name="Plant health contingency plans — generic and pest-specific (England)", Acronym="PH contingency plans", Record_Type="Policy_Activity",
 General_Type="Plan", Policy_Sector="Biosecurity | Land Use & Agriculture | Nature & Biodiversity", Year_Status="Generic plan May 2024; pest-specific plans 2015–2026",
 Statutory_Status="Mixed", Enabling_Legislation="[LEG-043]", Related_Policy_Links="[POL-034] Plant Biosecurity Strategy for GB; [POL-076] UK Plant Health Risk Register; [POL-033] Tree Health Resilience Strategy",
 Lead_Organisation="[ORG-001] Defra & [ORG-009] FC & [ORG-020] APHA",
 Scope_And_Commitments="Generic contingency plan for plant pest outbreaks in England, plus 24 pest-specific agricultural plans and 15 tree-health plans, setting out resources and response for the Plant Health Service. Defra works with the Met Office Hadley Centre on a climate-pest risk tool giving predicted pest emergence dates — a documented Met Office → policy channel.",
 Extent="England", Date_Last_Updated=D, Link="https://planthealthportal.defra.gov.uk/pests-and-diseases/contingency-planning/",
 _src="Defra plant health portal", _conf="High. Enabling links to the Plant Health Act 1967 and Plant Health (England) Order 2015 are inferred from the statutory basis of outbreak response, not stated on the page"),
P(Record_ID="POL-078", Name="30by30 on land in England — commitment, criteria and delivery plan", Acronym="30by30 England", Record_Type="Policy_Activity",
 General_Type="Plan", Policy_Sector="Nature & Biodiversity | Land Use & Agriculture", Year_Status="2026 (delivery plan 13 Jul 2026; criteria Oct 2024)",
 Statutory_Status="Non-statutory", Related_Policy_Links="[POL-022] 30×30 Technical Working Group; [POL-062] Landscape Recovery; [POL-097] Government Estate Nature Plan; [POL-001] EIP 2025",
 Lead_Organisation="[ORG-001] Defra & [ORG-005] NE",
 Scope_And_Commitments="Commitment to protect 30% of land in England for nature by 2030 (England's contribution to GBF Target 3). The delivery plan sets out routes including Protected Landscapes, Landscape Recovery and a National Estate for Nature, and a gold/silver/bronze tiered approach to assessing land, complementing the criteria published in 2024. SSSIs count only in favourable or recovering condition, so condition monitoring is integral. Separate approaches apply in Scotland ([POL-110]), Wales, NI and at sea. Assessment standard: [POL-079].",
 Extent="England", Date_Last_Updated=D, Link="https://www.gov.uk/government/publications/30by30-on-land-in-england-delivery-plan",
 Indicator_Frameworks="[IFW-01]; [IFW-05]", Intl_Links="[INT-L-007] Kunming-Montreal Global Biodiversity Framework",
 _src="gov.uk delivery plan page", _conf="High"),
P(Record_ID="POL-079", Name="30by30 on land — assessment guidance (criteria and gold/silver/bronze tiers)", Acronym="30by30 assessment", Record_Type="Policy_Activity",
 General_Type="Guidance / Methodology", Policy_Sector="Nature & Biodiversity | Land Use & Agriculture", Year_Status="2026 (published 13 Jul 2026)",
 Statutory_Status="Non-statutory", Parent_Programme="[POL-078] 30by30 on land in England", Lead_Organisation="[ORG-001] Defra",
 Scope_And_Commitments="How land is assessed for its contribution to 30by30 in England and reported against the national target: the three criteria (purpose, protection, management), gold/silver/bronze tiers, and central and partner assessment routes with a downloadable assessment form. An eligibility and assurance standard, not an indicator set: it creates no new monitoring and runs on existing SSSI, NNR and Landscape Recovery data. Its one headline measure is reported internationally through [GBF-013].",
 Extent="England", Date_Last_Updated=D, Link="https://www.gov.uk/government/publications/30by30-on-land-assessing-whether-land-can-contribute",
 _src="gov.uk guidance page (13 Jul 2026); criteria detail from the 17 Sep queue check, read in full then", _conf="High. Guidance / Methodology chosen over Standard / Code (your call per the queue)"),
P(Record_ID="POL-080", Name="Nature security assessment on global biodiversity loss, ecosystem collapse and national security", Acronym="Nature security assessment", Record_Type="Policy_Activity",
 General_Type="Assessment / Evidence", Policy_Sector="Nature & Biodiversity | Climate | Governance, Society & Data", Year_Status="2026 (published 20 Jan 2026)",
 Statutory_Status="Non-statutory", Related_Policy_Links="[POL-029] 2030 Strategic Framework for International Climate and Nature Action",
 Lead_Organisation="[ORG-001] Defra",
 Scope_And_Commitments="Cross-government assessment of how global biodiversity loss and ecosystem collapse could affect UK national security through food, water, health and supply-chain disruption and geopolitical instability. Identifies six ecosystems of strategic importance to the UK and their cascading impacts; supports long-term resilience planning.",
 Extent="UK | International", Date_Last_Updated=D, Link="https://www.gov.uk/government/publications/nature-security-assessment-on-global-biodiversity-loss-ecosystem-collapse-and-national-security",
 _src="gov.uk publication page", _conf="High"),
P(Record_ID="POL-081", Name="Farming Roadmap 2050: Growing England's Future (CP 1611)", Acronym="Farming Roadmap 2050", Record_Type="Policy_Activity",
 General_Type="Strategy / Framework", Policy_Sector="Land Use & Agriculture | Nature & Biodiversity | Climate", Year_Status="2026 (published 24 Jun 2026)",
 Statutory_Status="Non-statutory", Related_Policy_Links="[POL-013] ELM; [POL-054] SFI; [POL-061] CSHT; [POL-009] Land Use Framework",
 Lead_Organisation="[ORG-001] Defra",
 Scope_And_Commitments="Command Paper setting a direction to 2050 for a profitable, productive, sustainable and resilient farming sector in England, aligning government strategies for farmers and investors: productivity, environmental stewardship and nature recovery, net zero, and environmental land management support. With an evidence annex and a timeline to 2030.",
 Extent="England", Date_Last_Updated=D, Link="https://www.gov.uk/government/publications/farming-roadmap-2050",
 _src="gov.uk publication page", _conf="High"),
P(Record_ID="POL-082", Name="A new vision for water: white paper (CP 1940)", Acronym="Water White Paper 2026", Record_Type="Policy_Activity",
 General_Type="Strategy / Framework", Policy_Sector="Water | Nature & Biodiversity | Governance, Society & Data", Year_Status="2026 (published 20 Jan 2026; correction slip 19 Feb 2026)",
 Statutory_Status="Non-statutory", Related_Policy_Links="[POL-039] Independent Water Commission (Cunliffe Review); [POL-096] water demand target delivery plan",
 Lead_Organisation="[ORG-001] Defra",
 Scope_And_Commitments="Government's programme to reform the water sector around safe and secure supplies, a protected and enhanced environment, and fair outcomes for customers and investors, following the Independent Water Commission. Sets the direction for legislation and regulatory change. Borderline to scope; held because it is the major forthcoming legislative vehicle for water.",
 Extent="England", Date_Last_Updated=D, Link="https://www.gov.uk/government/publications/a-new-vision-for-water-white-paper",
 _src="gov.uk publication page", _conf="High on title, number, dates; regulator-reform detail not re-read, so not stated"),
P(Record_ID="POL-083", Name="Environment Act target delivery plans — overview", Acronym="EA21 TDPs", Record_Type="Policy_Activity",
 General_Type="Plan", Policy_Sector="Nature & Biodiversity | Water | Land Use & Agriculture | Marine & Fisheries | Pollution & Waste", Year_Status="2025 (first published 1 Dec 2025; updated 16 Jul 2026)",
 Statutory_Status="Mixed", Enabling_Legislation="[LEG-004]", Parent_Programme="[POL-001] Environmental Improvement Plan (EIP) 2025", Lead_Organisation="[ORG-001] Defra",
 Scope_And_Commitments="Overview of the thirteen delivery plans for the statutory targets set under the Environment Act 2021 and the interim targets in the Environmental Improvement Plan: agriculture water quality, air quality, farm wildlife, habitat creation and restoration, invasive non-native species, marine protected areas, protected sites, residual waste reduction, statutory species targets, tree canopy and woodland cover, wastewater, water and abandoned metal mines, and water demand ([POL-084]–[POL-096]). Latest delivery information is reported in the EIP annual progress report.",
 Extent="England", Date_Last_Updated=D, Link="https://www.gov.uk/government/publications/overview-delivery-plans-for-our-environment-act-targets", Indicator_Frameworks="[IFW-01]",
 _src="gov.uk overview page; EIP collection page (lists all 13)", _conf="High"),
]
_plans = [
 ("agriculture-water-quality","Agriculture water quality","Water | Land Use & Agriculture | Pollution & Waste","16 Jul 2026"),
 ("air-quality","Air quality","Pollution & Waste | Health","16 Jul 2026"),
 ("farm-wildlife","Farm wildlife","Nature & Biodiversity | Land Use & Agriculture","16 Jul 2026"),
 ("habitat-creation-and-restoration","Habitat creation and restoration","Nature & Biodiversity | Land Use & Agriculture","16 Jul 2026"),
 ("invasive-non-native-species","Invasive non-native species","Nature & Biodiversity | Biosecurity","16 Jul 2026"),
 ("marine-protected-areas-mpa","Marine protected areas (MPA)","Marine & Fisheries | Nature & Biodiversity","16 Jul 2026"),
 ("protected-sites","Protected sites","Nature & Biodiversity","20 Jul 2026"),
 ("residual-waste-reduction","Residual waste reduction","Pollution & Waste","16 Jul 2026"),
 ("statutory-species-targets","Statutory species targets","Nature & Biodiversity","16 Jul 2026"),
 ("tree-canopy-and-woodland-cover","Tree canopy and woodland cover","Nature & Biodiversity | Land Use & Agriculture | Climate","16 Jul 2026"),
 ("wastewater","Wastewater","Water | Pollution & Waste","26 Aug 2026"),
 ("water-and-abandoned-metal-mines","Water and abandoned metal mines","Water | Pollution & Waste","16 Jul 2026"),
 ("water-demand","Water demand","Water","16 Jul 2026"),
]
for i,(slug,topic,sec,upd) in enumerate(_plans):
    POL.append(P(Record_ID=f"POL-{84+i:03d}", Name=f"{topic} Environment Act target delivery plan", Acronym=f"EA21 TDP — {topic}",
      Record_Type="Policy_Activity", General_Type="Plan", Policy_Sector=sec,
      Year_Status=f"2025 (first published 1 Dec 2025; updated {upd})", Statutory_Status="Mixed", Enabling_Legislation="[LEG-004]",
      Parent_Programme="[POL-083] Environment Act target delivery plans — overview", Lead_Organisation="[ORG-001] Defra",
      Scope_And_Commitments=f"Delivery plan for the statutory and interim Environment Act 2021 targets relating to {topic.lower()}: policy delivery measures, evidence of impact and milestones. Interim targets are set in the Environmental Improvement Plan [POL-001]; progress is reported in the EIP annual progress report.",
      Extent="England", Date_Last_Updated=D, Link=f"https://www.gov.uk/government/publications/{slug}-environment-act-target-delivery-plan", Indicator_Frameworks="[IFW-01]",
      _src="EIP collection page; first-published date confirmed on the protected sites, water demand and wastewater pages", _conf="High on title, URL, dates; first-published date assumed 1 Dec 2025 for the ten pages not individually opened"))
POL += [
P(Record_ID="POL-097", Name="Government Estate Nature Plan (GENP)", Acronym="GENP", Record_Type="Policy_Activity",
 General_Type="Plan", Policy_Sector="Nature & Biodiversity | Land Use & Agriculture | Climate", Year_Status="2026 (published 26 Jun 2026)",
 Statutory_Status="Non-statutory", Related_Policy_Links="[POL-078] 30by30 on land in England; [POL-009] Land Use Framework", Lead_Organisation="[ORG-001] Defra",
 Scope_And_Commitments="A coordinated, whole-estate approach to restoring nature across government land in England, bringing departments together to embed nature recovery alongside operational delivery and to deliver nature recovery, climate resilience and public value. Applies Land Use Framework principles; relates to the National Estate for Nature in the 30by30 delivery plan.",
 Extent="England", Date_Last_Updated=D, Link="https://www.gov.uk/government/publications/government-estate-nature-plan-genp",
 _src="gov.uk publication page", _conf="High. Queue had 22 Jul 2026; source says 26 Jun 2026"),
P(Record_ID="POL-098", Name="The UK's approach to deforestation regulations", Acronym="UK deforestation regs", Record_Type="Policy_Activity",
 General_Type="Strategy / Framework", Policy_Sector="Nature & Biodiversity | Trade & Industry | Land Use & Agriculture", Year_Status="2026 (published 23 Jun 2026; updated 2 Sep 2026)",
 Statutory_Status="Mixed", Enabling_Legislation="[LEG-004]", Related_Policy_Links="[POL-029] 2030 Strategic Framework for International Climate and Nature Action",
 Lead_Organisation="[ORG-001] Defra",
 Scope_And_Commitments="Policy paper on tackling deforestation in UK supply chains: strengthening the global deforestation approach, seeking consistent regulation across the UK internal market, aligning with relevant frameworks such as the EU Deforestation Regulation (which applies in Northern Ireland from end-2026), and a planned consultation. Builds on the forest risk commodities powers in Schedule 17 to the Environment Act 2021.",
 Extent="UK", Date_Last_Updated=D, Link="https://www.gov.uk/government/publications/the-uks-approach-to-deforestation-regulations",
 _src="gov.uk publication page", _conf="High on dates and content; Schedule 17 link inherited (not stated on the landing page)"),
P(Record_ID="POL-099", Name="Biodiverse Landscapes Fund", Acronym="BLF", Record_Type="Policy_Activity",
 General_Type="Economic / market instrument", Policy_Sector="Nature & Biodiversity | Climate | Finance", Year_Status="2022–2029 (published 16 Dec 2021; updated 13 Aug 2026)",
 Statutory_Status="Non-statutory", Related_Policy_Links="[POL-029] 2030 Strategic Framework for International Climate and Nature Action", Lead_Organisation="[ORG-001] Defra",
 Scope_And_Commitments="International fund to protect and restore nature, tackle climate change and reduce poverty in globally important landscapes — Madagascar, Lower Mekong, Mesoamerica, Western Congo Basin and Andes-Amazon — running 2022 to 2029. Applications closed Feb 2023; grant agreements signed with delivery partners. Fund manager PwC; independent evaluators Oxford Policy Management and Itad.",
 Extent="UK | International", Date_Last_Updated=D, Link="https://www.gov.uk/government/publications/biodiverse-landscapes-fund",
 _src="gov.uk publication page", _conf="High. Fund size and ICF status not on the landing page, so not stated"),
P(Record_ID="POL-100", Name="Thames Estuary 2100 (TE2100) Plan and monitoring reviews", Acronym="TE2100", Record_Type="Policy_Activity",
 General_Type="Plan", Policy_Sector="Water | Climate | Urban & Buildings", Year_Status="2012 (major update 2023; 15-year monitoring review Aug 2026)",
 Statutory_Status="Non-statutory", Related_Policy_Links="[POL-045] FCERM Strategy; [POL-070] NaFRA2; [POL-002] NAP3", Lead_Organisation="[ORG-006] EA",
 Scope_And_Commitments="Environment Agency adaptive plan for managing tidal flood risk in the Thames Estuary to 2100 across 23 policy units, designed around sea-level rise with five-, ten- and fifteen-year monitoring reviews that test whether the adaptation pathway must change. Included deliberately as a worked example of adaptive climate management with a formal monitoring cycle, although estuary-specific plans are generally out of scope — do not remove as inconsistent.",
 Extent="England", Date_Last_Updated=D, Link="https://www.gov.uk/government/collections/thames-estuary-2100-te2100",
 _src="gov.uk collection page", _conf="High"),
P(Record_ID="POL-101", Name="The Blue Belt Programme", Acronym="Blue Belt", Record_Type="Policy_Activity",
 General_Type="Scheme / Programme", Policy_Sector="Marine & Fisheries | Nature & Biodiversity | Climate", Year_Status="2016–ongoing (guidance first published 24 Oct 2017; updated 13 Aug 2026)",
 Statutory_Status="Non-statutory", Lead_Organisation="[ORG-039] FCDO & [ORG-018] Cefas & [ORG-008] MMO",
 Scope_And_Commitments="UK government programme supporting UK Overseas Territories to protect and enhance more than 4 million km² of marine environment: biodiversity protection, governance, managing human impacts, compliance and enforcement, and capacity building, including climate resilience. Funded 2022–2025 through the FCDO International Programme Fund; delivered by Cefas and the MMO.",
 Extent="UK | International", Date_Last_Updated=D, Link="https://www.gov.uk/guidance/the-blue-belt-programme",
 _src="gov.uk guidance page", _conf="High. Lead is FCDO, not Defra as the queue assumed"),
P(Record_ID="POL-102", Name="Peatland Restoration Sector Capacity Grant Scheme (England)", Acronym="PRSCG", Record_Type="Policy_Activity",
 General_Type="Economic / market instrument", Policy_Sector="Nature & Biodiversity | Climate | Land Use & Agriculture", Year_Status="2026–2030 (opened 11 Jun 2026)",
 Statutory_Status="Non-statutory", Related_Policy_Links="[POL-010] England Peat Action Plan 2021; [POL-040] Nature for Climate Fund", Lead_Organisation="[ORG-001] Defra",
 Scope_And_Commitments="£1.15m over 2026–2030 (grants up to £20,000 a year) to remove barriers to peatland restoration by building sector capacity — specialist machinery, apprenticeships, training, equipment and engagement. Supports the EIP commitment to restore 40,000 ha by April 2030 and the 280,000 ha by 2050 target; complements the Nature for Climate Peatland Grant Scheme.",
 Extent="England", Date_Last_Updated=D, Link="https://www.find-government-grants.service.gov.uk/grants/peatland-restoration-sector-capacity-grant-scheme-1",
 _src="Find a Grant listing; Defra environment blog 19 May 2026", _conf="High"),
P(Record_ID="POL-103", Name="National Framework for Water Resources 2025: water for growth, nature and a resilient future", Acronym="NFWR 2025", Record_Type="Policy_Activity",
 General_Type="Strategy / Framework", Policy_Sector="Water | Climate | Nature & Biodiversity", Year_Status="2025 (published 17 Jun 2025; updated 27 Aug 2026)",
 Statutory_Status="Mixed", Enabling_Legislation="[LEG-012]", Related_Policy_Links="[POL-082] Water White Paper 2026; [POL-096] water demand target delivery plan", Lead_Organisation="[ORG-006] EA",
 Scope_And_Commitments="Environment Agency assessment of England's long-term water needs to 2055 and the scale of action needed for resilient supplies and an improved water environment: national water need across public supply, energy and food production, climate-change impacts on availability, expectations for regional water resources planning, and the Environmental Destination for abstraction. Informs statutory water resources management plans.",
 Extent="England | Wales", Date_Last_Updated=D, Link="https://www.gov.uk/government/publications/national-framework-for-water-resources-2025-water-for-growth-nature-and-a-resilient-future",
 _src="gov.uk publication page", _conf="High on content; Mixed/[LEG-012] reflects the statutory WRMP regime it informs (inferred). Queue had 27 Aug 2026 — that is the update date"),
P(Record_ID="POL-104", Name="Species Recovery Programme (Natural England)", Acronym="SRP", Record_Type="Policy_Activity",
 General_Type="Scheme / Programme", Policy_Sector="Nature & Biodiversity", Year_Status="Ongoing (2026–2029 funded projects published 8 Jul 2026)",
 Statutory_Status="Non-statutory", Related_Policy_Links="[POL-092] statutory species targets delivery plan", Lead_Organisation="[ORG-005] NE",
 Scope_And_Commitments="Natural England programme of targeted action for threatened species with specific recovery needs, to prevent national extinctions. 2026–2029 projects funded following a 2025 call; over half the species are Near Threatened, Vulnerable or Endangered on the GB Red List. Supports the Environment Act 2021 target to reduce species extinction risk by 2042 compared with 2022.",
 Extent="England", Date_Last_Updated=D, Link="https://www.gov.uk/government/publications/species-recovery-programme-projects-awarded-funding-for-2026-to-2029",
 _src="gov.uk publication page", _conf="High. Funding total and project count not on the landing page, so not stated"),
P(Record_ID="POL-105", Name="Local Sites (Local Wildlife Sites and Local Geological Sites) — selection and management", Acronym="Local Sites", Record_Type="Policy_Activity",
 General_Type="Guidance / Methodology", Policy_Sector="Nature & Biodiversity | Land Use & Agriculture", Year_Status="Guidance published 10 Aug 2026 (updated 1 Oct 2026)",
 Statutory_Status="Non-statutory", Related_Policy_Links="[POL-050] NPPF; [POL-014] LNRS", Lead_Organisation="[ORG-005] NE",
 Scope_And_Commitments="Non-statutory sites of substantive nature conservation value selected locally by Local Sites partnerships using consistent ecological and geological criteria; not legally protected and reliant on local policy and planning decisions. The tier of site designation below SSSI. Guidance sets selection, management and data-recording standards.",
 Extent="England", Date_Last_Updated=D, Link="https://www.gov.uk/guidance/selecting-and-managing-local-sites",
 _src="gov.uk guidance page", _conf="High. NPPF link is a soft relation (planning reliance), not quoted from the page"),
P(Record_ID="POL-106", Name="Northern Ireland Peatland Strategy to 2040", Acronym="NI Peatland Strategy", Record_Type="Policy_Activity",
 General_Type="Strategy / Framework", Policy_Sector="Nature & Biodiversity | Climate | Land Use & Agriculture | Water", Year_Status="2025 (published 17 Sep 2025; first Delivery Plan 22 Apr 2026)",
 Statutory_Status="Non-statutory", Related_Policy_Links="[POL-010] England Peat Action Plan 2021; [POL-066] Peatland ACTION (Scotland)", Lead_Organisation="[ORG-036] Northern Ireland Executive (DAERA)",
 Scope_And_Commitments="Framework to guide the conservation and restoration of peatland habitats in Northern Ireland to 2040, aiming for all peatland to be conserved, restored or appropriately managed by 2040, for biodiversity, climate mitigation and green growth. First Delivery Plan (Apr 2026–Dec 2027) has 14 short-term targets incl. a Peatland Asset Register and 4,500 ha recovering; later plans follow five-year Climate Action Plan cycles. Evidence base includes JNCC Report 828, Peatland Impact Assessment, produced for DAERA (3 Aug 2026).",
 Extent="Northern Ireland", Date_Last_Updated=D, Link="https://www.daera-ni.gov.uk/publications/northern-ireland-peatland-strategy-2040",
 _src="DAERA publication page; DAERA delivery-plan news; JNCC news 3 Aug 2026", _conf="High. REPLACES the queued row 'JNCC evidence review on NI peatland restoration' — a single report fails the level-of-generality rule; the strategy it serves had no record"),
P(Record_ID="POL-107", Name="Independent Review of Greenhouse Gas Removals and government response", Acronym="GGR Review", Record_Type="Policy_Activity",
 General_Type="Independent Review / Inquiry", Policy_Sector="Climate | Energy | Land Use & Agriculture | Nature & Biodiversity", Year_Status="Review Oct 2025 (chair Dr Alan Whitehead); government response 17 Jul 2026",
 Statutory_Status="Non-statutory", Related_Policy_Links="[POL-018] Seventh Carbon Budget; [POL-009] Land Use Framework; [POL-048] Biomass Strategy 2023", Lead_Organisation="[ORG-002] DESNZ",
 Scope_And_Commitments="Independent review of how the UK deploys greenhouse gas removals, and the government's response. Covers engineered removals (BECCS, DACCS, biochar, enhanced rock weathering, mineralisation) and nature-based removals (woodland creation, peat, soil carbon). Response commits to a GGR business model, integrating GGRs into the UK ETS, a UK GGR standard, considering the land-use requirements of biomass, and the review's aim to minimise imported biomass feedstocks. The habitat implications run through woodland, peat and biomass land use.",
 Extent="UK", Date_Last_Updated=D, Link="https://www.gov.uk/government/publications/independent-review-on-greenhouse-gas-removals-government-response",
 _src="gov.uk review page; government response page", _conf="High. Answers your 11 Sep question: yes — the response explicitly covers nature-based removals and biomass land use"),
P(Record_ID="POL-108", Name="Scottish Biodiversity Strategy to 2045: Tackling the Nature Emergency", Acronym="SBS 2045", Record_Type="Policy_Activity",
 General_Type="Strategy / Framework", Policy_Sector="Nature & Biodiversity | Marine & Fisheries | Land Use & Agriculture | Climate", Year_Status="2024 (final strategy published Nov 2024 with the Delivery Plan; draft Dec 2022)",
 Statutory_Status="Statutory", Enabling_Legislation="[LEG-032]", Related_Policy_Links="[POL-003] UK NBSAP 2025", Lead_Organisation="[ORG-034] Scottish Government & [ORG-014] NatureScot",
 Scope_And_Commitments="Scotland's strategic biodiversity framework: halt biodiversity loss by 2030 and restore and regenerate biodiversity across land, freshwater and sea by 2045. Delivered through five-year rolling delivery plans ([POL-109]), statutory nature restoration targets under the Natural Environment (Scotland) Act 2026 [LEG-068], an investment plan and a reporting framework. Governance: a ministerially chaired Strategic Biodiversity Council, an operational delivery board co-chaired by the Scottish Government and NatureScot, and topic working groups. Scotland's counterpart to England's EIP [POL-001].",
 Extent="Scotland", Date_Last_Updated=D, Link="https://www.gov.scot/publications/scottish-biodiversity-strategy-2045/",
 _src="gov.scot strategy pages (governance and targets); gov.scot search listing (Nov 2024 final PDF)", _conf="MEDIUM on dates: the final strategy page would not render; Nov 2024 inferred from the publication path; statutory basis (2004 Act s.2 duty to designate a strategy) inherited"),
P(Record_ID="POL-109", Name="Scottish Biodiversity Delivery Plan 2024–2030", Acronym="SBDP 2024–30", Record_Type="Policy_Activity",
 General_Type="Plan", Policy_Sector="Nature & Biodiversity | Marine & Fisheries | Land Use & Agriculture", Year_Status="2024 (published 27 Nov 2024)",
 Statutory_Status="Mixed", Enabling_Legislation="[LEG-032]", Parent_Programme="[POL-108] Scottish Biodiversity Strategy to 2045", Lead_Organisation="[ORG-034] Scottish Government",
 Scope_And_Commitments="First five-year delivery plan under the Scottish Biodiversity Strategy, with six objectives: accelerate ecosystem restoration and regeneration; protect nature on land and at sea, across and beyond protected areas (incl. 30 by 30, [POL-110]); embed nature-positive farming, fishing and forestry; protect and support recovery of vulnerable species and habitats; invest in nature; address indirect drivers of biodiversity loss. Accompanied by a governance, monitoring and evaluation framework.",
 Extent="Scotland", Date_Last_Updated=D, Link="https://www.gov.scot/publications/scottish-biodiversity-delivery-plan-20242030/",
 _src="gov.scot publication page", _conf="High"),
P(Record_ID="POL-110", Name="30 by 30 in Scotland (framework and Nature30 criteria)", Acronym="30 by 30 Scotland", Record_Type="Policy_Activity",
 General_Type="Strategy / Framework", Policy_Sector="Nature & Biodiversity | Marine & Fisheries | Land Use & Agriculture", Year_Status="2023 (framework)",
 Statutory_Status="Non-statutory", Parent_Programme="[POL-108] Scottish Biodiversity Strategy to 2045", Related_Policy_Links="[POL-022] 30×30 Technical Working Group; [POL-078] 30by30 on land in England",
 Lead_Organisation="[ORG-034] Scottish Government & [ORG-014] NatureScot",
 Scope_And_Commitments="Scotland's commitment that at least 30% of land, inland water and coastal and marine areas are effectively conserved and managed by 2030, through protected areas and OECMs ('Nature30' sites), with NatureScot leading implementation across six themes including monitoring. About 18% of land and freshwater and 37% of sea in protected areas at the framework's date. Separate from England's commitment [POL-078].",
 Extent="Scotland", Date_Last_Updated=D, Link="https://www.nature.scot/doc/framework-30-30-scotland",
 Indicator_Frameworks="[IFW-05]", Intl_Links="[INT-L-007] Kunming-Montreal Global Biodiversity Framework",
 _src="nature.scot framework page", _conf="High on commitment and leadership; coverage figures are the framework's own, not current"),
]

# Edits to existing records: (workbook, sheet, Record_ID, column, old_contains, new_value, reason)
EDITS = [
("uk","Public Bodies","ORG-031","Statutory_Role","[LEG-059]","[LEG-059]; [LEG-071]","Authority for the office (queued with ORG-031 corrections)"),
("uk","Legislation","LEG-034","Name","Environment (Scotland) Act 2023","UK Withdrawal from the European Union (Continuity) (Scotland) Act 2021","CORRECTION — see below"),
("uk","Legislation","LEG-034","Year","2023","2021",""),
("uk","Legislation","LEG-034","Statutory_Enabling_Basis",None,"Primary Act of the Scottish Parliament (2021 asp 4) — self-authorising.",""),
("uk","Legislation","LEG-034","Key_Provisions",None,"Part 2 Chapter 1 imposes a duty on Scottish Ministers and other authorities to have due regard to the guiding environmental principles; Part 2 Chapter 2 (s.19) establishes Environmental Standards Scotland [ORG-045] to scrutinise compliance with and the effectiveness of environmental law. Part 1 gives Ministers powers to keep Scots law aligned with EU law. Repurposed in v27 from a non-existent 'Environment (Scotland) Act 2023' record whose provisions described this Act; ID kept so inbound references stay intact.",""),
("uk","Legislation","LEG-034","Status",None,"In force",""),
("uk","Legislation","LEG-034","Link","https://www.legislation.gov.uk/asp/2023/4/contents","https://www.legislation.gov.uk/asp/2021/4/contents","Old link resolves to the Bail and Release from Custody (Scotland) Act 2023"),
("uk","Public Bodies","ORG-014","Statutory_Role","[LEG-032]; [LEG-033]; [LEG-034]","[LEG-032]; [LEG-033]","The Continuity Act does not establish or empower NatureScot"),
]
EDITS_INTL = [
("intl","Conventions & Treaties","INT-L-007","UK_Links","append","; [POL-078] 30by30 on land in England; [POL-110] 30 by 30 in Scotland","Reciprocal for the two new Intl_Links (invariant 3)"),
]
VOCAB = [("uk","Policies & Activities","General_Type","Operational service / System","Agreed by Jonathan 10 Sep 2026 (D2); used by POL-072, POL-075, POL-076")]

NOT_WRITTEN = [
("Nature Recovery Strategy for Northern Ireland to 2032","Still a draft: consultation closed (extended) Apr–May 2026, no final strategy published. Keep 'add' pending adoption."),
("Scottish Biodiversity Programme (queued as ORG)","No body or programme of that name in the current strategy or delivery plan; governance is a Strategic Biodiversity Council and a delivery board, recorded in the POL-108 prose. Recommend 'rejected' with that reason."),
("Memorandum of Understanding CCC–ESS (23 Jul 2026)","Recorded as a sentence in ORG-045 (ESS) rather than a record — a relationship, not a policy."),
("JNCC evidence review on NI peatland restoration","Replaced by POL-106 NI Peatland Strategy to 2040; the report is cited in its prose."),
("Taxation (Energy and Vehicles) Act 2026; Finance Act 2026; English Devolution and Community Empowerment Act 2026; 2026 Acts audit finding","Your decision: fold into the legislative backlog audit (D8), not piecemeal. Separate job."),
("EIF currency; CCC Adaptation framework; Monitoring the condition (POL-071); NaFRA2 (POL-070); FCERM statistic","Already done or decided 'no action'. Status corrected in the queue only."),
]
